# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/comen_lab/practice_3/practice_3.srcs/sources_1/ip/mmcm_50m/mmcm_50m.xci
# IP: The module: 'mmcm_50m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/comen_lab/practice_3/practice_3.gen/sources_1/ip/mmcm_50m/mmcm_50m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_50m'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/comen_lab/practice_3/practice_3.gen/sources_1/ip/mmcm_50m/mmcm_50m.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_50m'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/comen_lab/practice_3/practice_3.gen/sources_1/ip/mmcm_50m/mmcm_50m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_50m'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/comen_lab/practice_3/practice_3.srcs/sources_1/ip/mmcm_50m/mmcm_50m.xci
# IP: The module: 'mmcm_50m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/comen_lab/practice_3/practice_3.gen/sources_1/ip/mmcm_50m/mmcm_50m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_50m'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/comen_lab/practice_3/practice_3.gen/sources_1/ip/mmcm_50m/mmcm_50m.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_50m'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/comen_lab/practice_3/practice_3.gen/sources_1/ip/mmcm_50m/mmcm_50m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_50m'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
