# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/comen_lab/practice_4/practice_4.srcs/sources_1/ip/fifo_8bit/fifo_8bit.xci
# IP: The module: 'fifo_8bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/comen_lab/practice_4/practice_4.gen/sources_1/ip/fifo_8bit/fifo_8bit.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8bit'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/comen_lab/practice_4/practice_4.gen/sources_1/ip/fifo_8bit/fifo_8bit_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/comen_lab/practice_4/practice_4.gen/sources_1/ip/fifo_8bit/fifo_8bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/comen_lab/practice_4/practice_4.srcs/sources_1/ip/fifo_8bit/fifo_8bit.xci
# IP: The module: 'fifo_8bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/comen_lab/practice_4/practice_4.gen/sources_1/ip/fifo_8bit/fifo_8bit.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/comen_lab/practice_4/practice_4.gen/sources_1/ip/fifo_8bit/fifo_8bit_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/comen_lab/practice_4/practice_4.gen/sources_1/ip/fifo_8bit/fifo_8bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
