# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/comen_lab/practice_2/practice_2.srcs/sources_1/ip/ila_uart/ila_uart.xci
# IP: The module: 'ila_uart' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/comen_lab/practice_2/practice_2.gen/sources_1/ip/ila_uart/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uart'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/comen_lab/practice_2/practice_2.gen/sources_1/ip/ila_uart/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/comen_lab/practice_2/practice_2.gen/sources_1/ip/ila_uart/ila_uart_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/comen_lab/practice_2/practice_2.srcs/sources_1/ip/ila_uart/ila_uart.xci
# IP: The module: 'ila_uart' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/comen_lab/practice_2/practice_2.gen/sources_1/ip/ila_uart/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/comen_lab/practice_2/practice_2.gen/sources_1/ip/ila_uart/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/comen_lab/practice_2/practice_2.gen/sources_1/ip/ila_uart/ila_uart_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
